### ISSUE TITLE
Better Error Handling on incorrect EXTERNAL_INPUT argument

### ISSUE THREAD

**Issue by a-bash** [VaultTree/vault-tree#16]
Steps to reproduce:
* when closing a vault pass a key in the external data hash that is different from the `EXTERNAL_INPUT['argument']` 'argument' name
* You will see something like the following

```
/Users/abashelor/.rvm/gems/ruby-2.1.4/gems/rbnacl-3.1.2/lib/rbnacl/util.rb:33:in `+': no implicit conversion of nil into String (TypeError)
	from /Users/abashelor/.rvm/gems/ruby-2.1.4/gems/rbnacl-3.1.2/lib/rbnacl/util.rb:33:in `prepend_zeros'
	from /Users/abashelor/.rvm/gems/ruby-2.1.4/gems/rbnacl-3.1.2/lib/rbnacl/secret_boxes/xsalsa20poly1305.rb:67:in `box'
	from /Users/abashelor/.rvm/gems/ruby-2.1.4/gems/rbnacl-3.1.2/lib/rbnacl/simple_box.rb:78:in `box'
	from /Users/abashelor/vault-tree/lib/vault-tree/lock_smith.rb:45:in `symmetric_encrypt'
	from /Users/abashelor/vault-tree/lib/vault-tree/contract/content_ciphertext.rb:21:in `symmetric_ciphertext'
	from /Users/abashelor/vault-tree/lib/vault-tree/contract/content_ciphertext.rb:11:in `evaluate'
	from /Users/abashelor/vault-tree/lib/vault-tree/contract/vault.rb:42:in `ciphertext'
	from /Users/abashelor/vault-tree/lib/vault-tree/contract/vault.rb:34:in `locked_contents'
	from /Users/abashelor/vault-tree/lib/vault-tree/contract/vault.rb:12:in `close'
	from /Users/abashelor/vault-tree/lib/vault-tree/contract/vault_list.rb:13:in `close_vault'
	from /Users/abashelor/vault-tree/lib/vault-tree/contract/contract.rb:14:in `close_vault'
	from scripts/lock_vault.rb:22:in `<main>'
```

Fix:
* Better defense in this case
* Explicit Vault Tree notification

**Comment by a-bash** [comment]
No Longer Relavent. Closing.
